### ISSUE TITLE
Azure DSVM(ubuntu 18.04) can't run ExplanationDashboard

### ISSUE THREAD

**Issue by darrenyu1111** [interpretml/interpret-community#308]
**Describe the bug**
Azure DSVM(ubuntu 18.04) can't run ExplanationDashboard
![pic1](https://user-images.githubusercontent.com/69653377/90190358-b53ef100-dd73-11ea-9be9-39b420e7d159.jpg)

**To Reproduce**
1. creating the data science VM-ubuntu 18.04 resources;
2. running interpretability script , reference scripts from https://github.com/interpretml/interpret-community/blob/master/notebooks/explain-regression-local.ipynb;
3. After running the following script, a visualization panel will appear in the Jupypter notebook environment (see the figure),
 from interpret_community.widget import ExplanationDashboard
 ExplanationDashboard(global_explanation, model, datasetX=x_test) 
4.   But after clicking "Open in new tab" in the output visualization panel, the IP address of the created VM public network cannot be located, but it is directly located to http://localhost:5001/1, so the model cannot be accessed in the browser Interpretability panel.

**Expected behavior**
it shall navigate to the public IP address of azure DSVM

**Screenshots**
see the attachment

**Desktop (please complete the following information):**
 - OS : ubuntu 18.04
 - Browser : chrome
 
**Smartphone (please complete the following information):**
not applicable 

**Additional context**

**Comment by imatiach-msft** [comment]
@darrenyu1111 can you try the latest version of interpret-community, 0.14.3?  There should be a "public_ip" parameter on the Explanation Dashboard, which you can set as the DSVM address, and this should work - as well as what if analysis and ICE plots.

**Comment by imatiach-msft** [comment]
https://github.com/interpretml/interpret-community/blob/master/python/interpret_community/widget/explanation_dashboard.py#L72

**Comment by darrenyu1111** [comment]
@imatiach-msft 
  I updated it, and it does not navigate to VM IP address, and it is still using "http://localhost:5001" as a linkage for open new tab.
see the attached file.
![pic2](https://user-images.githubusercontent.com/69653377/90197305-233ee480-dd83-11ea-83e5-e87f412dfe7c.jpg)

**Comment by imatiach-msft** [comment]
@darrenyu1111 will take another look, thank you for finding the issue

**Comment by imatiach-msft** [comment]
@darrenyu1111 I was able to reproduce the issue and fix it in this PR: https://github.com/interpretml/interpret-community/pull/309
I've merged the PR and will do a new release soon.  Currently trying to get a couple more fixes in before doing the release.

**Comment by imatiach-msft** [comment]
@darrenyu1111 I just did the new 0.14.4 release to pypi with the PR fix for you, does that fix your issue?

**Comment by darrenyu1111** [comment]
@imatiach-msft  I upgraded to 0.14.4 and added public IP address as param,  it looks public IP address(Azure DSVM)can be showed up through "open in new tab" , but visualization dashboard is still not accessible from remote client's chrome after click"open in new tab".  the error in the browser : 
This site can’t be reached xxxx.xxxx.xxxx.xxxx took too long to respond.
Try:
Checking the connection
Checking the proxy and the firewall
Running Windows Network Diagnostics
ERR_CONNECTION_TIMED_OUT

**Comment by imatiach-msft** [comment]
@darrenyu1111 hmm strange, when clicking "open in new tab" on Azure DSVM it seemed to work for me.  I wonder if there is something about how the VM was setup that is causing this issue.  You only set public_ip parameter and nothing else, is that correct?  I wonder if it might have something to do with the port configuration.

**Comment by darrenyu1111** [comment]
@imatiach-msft yes, it's working now. FW of VM causes the issue.

**Comment by imatiach-msft** [comment]
@darrenyu1111 great to hear it is resolved, closing this github issue #308 tracking the problem

**Comment by darrenyu1111** [comment]
@imatiach-msft , when I run the scripts on another .ipynb in VM simultaneously, there is error message below, 
could it support multiple .ipynb run?

Exception in thread Thread-35:
Traceback (most recent call last):
  File "/opt/tljh/user/lib/python3.7/threading.py", line 926, in _bootstrap_inner
    self.run()
  File "/opt/tljh/user/lib/python3.7/threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "/home/jupyter-jupyteradmin/.local/lib/python3.7/site-packages/interpret_community/widget/explanation_dashboard.py", line 176, in run
    server.serve_forever()
  File "/home/jupyter-jupyteradmin/.local/lib/python3.7/site-packages/gevent/baseserver.py", line 398, in serve_forever
    self.start()
  File "/home/jupyter-jupyteradmin/.local/lib/python3.7/site-packages/gevent/baseserver.py", line 336, in start
    self.init_socket()
  File "/home/jupyter-jupyteradmin/.local/lib/python3.7/site-packages/gevent/pywsgi.py", line 1500, in init_socket
    StreamServer.init_socket(self)
  File "/home/jupyter-jupyteradmin/.local/lib/python3.7/site-packages/gevent/server.py", line 180, in init_socket
    self.socket = self.get_listener(self.address, self.backlog, self.family)
  File "/home/jupyter-jupyteradmin/.local/lib/python3.7/site-packages/gevent/server.py", line 192, in get_listener
    return _tcp_listener(address, backlog=backlog, reuse_addr=cls.reuse_addr, family=family)
  File "/home/jupyter-jupyteradmin/.local/lib/python3.7/site-packages/gevent/server.py", line 288, in _tcp_listener
    sock.bind(address)
OSError: [Errno 98] Address already in use: ('10.0.2.5', 5000)
